include: package:lint/strict.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/rust/**"
    - "rust_builder/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - custom_lint

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: false
    unawaited_futures: true
