targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/model/**.dart
            - lib/rust/**.dart
          exclude:
            - "**.freezed.dart"
            - "**.g.dart"
      json_serializable:
        generate_for:
          include:
            - lib/model/**.dart
          exclude:
            - "**.freezed.dart"
            - "**.g.dart"
        options:
          explicit_to_json: true
          include_if_null: false
      riverpod_generator:
        generate_for:
          include:
            - lib/provider/**.dart
            - lib/router/**.dart
          exclude:
            - "**.g.dart"
        options:
          provider_name_strip_pattern: ""
      slang_build_runner:
        options:
          base_locale: en-US
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.yaml
          output_directory: lib/i18n
          namespaces: true
          string_interpolation: braces
          flat_map: false
          timestamp: false
