import 'dart:collection';
import 'dart:convert';
import 'dart:io';

void main() {
  const categories = [
    'face',
    'people',
    'animals_and_nature',
    'food_and_drink',
    'activity',
    'travel_and_places',
    'objects',
    'symbols',
    'flags',
  ];
  const emojilist = [
    ['🙂‍↔️', 'head_shaking_horizontally', 0],
    ['🙂‍↕️', 'head_shaking_vertically', 0],
    ['🚶‍➡️', 'person_walking_facing_right', 1],
    ['🚶‍♀️‍➡️', 'woman_walking_facing_right', 1],
    ['🚶‍♂️‍➡️', 'man_walking_facing_right', 1],
    ['🧎‍➡️', 'person_kneeling_facing_right', 1],
    ['🧎‍♀️‍➡️', 'woman_kneeling_facing_right', 1],
    ['🧎‍♂️‍➡️', 'man_kneeling_facing_right', 1],
    ['🧑‍🦯‍➡️', 'person_with_white_cane_facing_right', 1],
    ['👨‍🦯‍➡️', 'man_with_white_cane_facing_right', 1],
    ['👩‍🦯‍➡️', 'woman_with_white_cane_facing_right', 1],
    ['🧑‍🦼‍➡️', 'person_in_motorized_wheelchair_facing_right', 1],
    ['👨‍🦼‍➡️', 'man_in_motorized_wheelchair_facing_right', 1],
    ['👩‍🦼‍➡️', 'woman_in_motorized_wheelchair_facing_right', 1],
    ['🧑‍🦽‍➡️', 'person_in_manual_wheelchair_facing_right', 1],
    ['👨‍🦽‍➡️', 'man_in_manual_wheelchair_facing_right', 1],
    ['👩‍🦽‍➡️', 'woman_in_manual_wheelchair_facing_right', 1],
    ['🏃‍➡️', 'person_running_facing_right', 1],
    ['🏃‍♀️‍➡️', 'woman_running_facing_right', 1],
    ['🏃‍♂️‍➡️', 'man_running_facing_right', 1],
    ['🧑‍🧑‍🧒', 'family_adult_adult_child', 1],
    ['🧑‍🧑‍🧒‍🧒', 'family_adult_adult_child_child', 1],
    ['🧑‍🧒', 'family_adult_child', 1],
    ['🧑‍🧒‍🧒', 'family_adult_child_child', 1],
    ['🐦‍🔥', 'phoenix', 2],
    ['🍋‍🟩', 'lime', 3],
    ['🍄‍🟫', 'brown_mushroom', 3],
    ['⛓️‍💥', 'broken_chain', 6],
    ['🇦', 'regional_indicator_a', 7],
    ['🇧', 'regional_indicator_b', 7],
    ['🇨', 'regional_indicator_c', 7],
    ['🇩', 'regional_indicator_d', 7],
    ['🇪', 'regional_indicator_e', 7],
    ['🇫', 'regional_indicator_f', 7],
    ['🇬', 'regional_indicator_g', 7],
    ['🇭', 'regional_indicator_h', 7],
    ['🇮', 'regional_indicator_i', 7],
    ['🇯', 'regional_indicator_j', 7],
    ['🇰', 'regional_indicator_k', 7],
    ['🇱', 'regional_indicator_l', 7],
    ['🇲', 'regional_indicator_m', 7],
    ['🇳', 'regional_indicator_n', 7],
    ['🇴', 'regional_indicator_o', 7],
    ['🇵', 'regional_indicator_p', 7],
    ['🇶', 'regional_indicator_q', 7],
    ['🇷', 'regional_indicator_r', 7],
    ['🇸', 'regional_indicator_s', 7],
    ['🇹', 'regional_indicator_t', 7],
    ['🇺', 'regional_indicator_u', 7],
    ['🇻', 'regional_indicator_v', 7],
    ['🇼', 'regional_indicator_w', 7],
    ['🇽', 'regional_indicator_x', 7],
    ['🇾', 'regional_indicator_y', 7],
    ['🇿', 'regional_indicator_z', 7],
  ];
  final unicodeEmojiIndexes = <String, Map<String, List<String>>>{
    'en-US': {
      '😶‍🌫️': [
        'face_in_clouds',
        'absentminded',
        'clouds',
        'face',
        'fog',
        'head',
      ],
      '😮‍💨': [
        'face_exhaling',
        'blow',
        'blowing',
        'exhale',
        'exhaling',
        'exhausted',
        'face',
        'gasp',
        'groan',
        'relief',
        'sigh',
        'smiley',
        'smoke',
        'whisper',
        'whistle',
      ],
      '🙂‍↔️': [
        'head_shaking_horizontally',
        'head',
        'horizontally',
        'no',
        'shake',
        'shaking',
      ],
      '🙂‍↕️': [
        'head_shaking_vertically',
        'head',
        'nod',
        'shaking',
        'vertically',
        'yes',
      ],
      '😵‍💫': [
        'face_with_spiral_eyes',
        'confused',
        'dizzy',
        'eyes',
        'face',
        'hypnotized',
        'omg',
        'smiley',
        'spiral',
        'trouble',
        'whoa',
        'woah',
        'woozy',
      ],
      '🫱': [
        'rightwards_hand',
        'hand',
        'handshake',
        'hold',
        'reach',
        'right',
        'rightward',
        'rightwards',
        'shake',
      ],
      '🫲': [
        'leftwards_hand',
        'hand',
        'handshake',
        'hold',
        'left',
        'leftward',
        'leftwards',
        'reach',
        'shake',
      ],
      '🫳': [
        'palm_down_hand',
        'dismiss',
        'down',
        'drop',
        'dropped',
        'hand',
        'palm',
        'pick',
        'shoo',
        'up',
      ],
      '🫴': [
        'palm_up_hand',
        'beckon',
        'catch',
        'come',
        'hand',
        'hold',
        'know',
        'lift',
        'me',
        'offer',
        'palm',
        'tell',
      ],
      '🫰': [
        'hand_with_index_finger_and_thumb_crossed',
        '<3',
        'crossed',
        'expensive',
        'finger',
        'hand',
        'heart',
        'index',
        'love',
        'money',
        'snap',
        'thumb',
      ],
      '🫵': [
        'index_pointing_at_the_viewer',
        'at',
        'finger',
        'hand',
        'index',
        'pointing',
        'poke',
        'viewer',
        'you',
      ],
      '🫀': [
        'anatomical_heart',
        'anatomical',
        'beat',
        'cardiology',
        'heart',
        'heartbeat',
        'organ',
        'pulse',
        'real',
        'red',
      ],
      '🫁': [
        'lungs',
        'breath',
        'breathe',
        'exhalation',
        'inhalation',
        'lung',
        'lungs',
        'organ',
        'respiration',
      ],
      '🫦': [
        'biting_lip',
        'anxious',
        'bite',
        'biting',
        'fear',
        'flirt',
        'flirting',
        'kiss',
        'lip',
        'lipstick',
        'nervous',
        'sexy',
        'uncomfortable',
        'worried',
        'worry',
      ],
      '🥷': [
        'ninja',
        'assassin',
        'fight',
        'fighter',
        'hidden',
        'ninja',
        'person',
        'secret',
        'skills',
        'sly',
        'soldier',
        'stealth',
        'war',
      ],
      '🫅': [
        'person_with_crown',
        'crown',
        'monarch',
        'noble',
        'person',
        'regal',
        'royal',
        'royalty',
      ],
      '🫃': [
        'pregnant_man',
        'belly',
        'bloated',
        'full',
        'man',
        'overeat',
        'pregnant',
      ],
      '🫄': [
        'pregnant_person',
        'belly',
        'bloated',
        'full',
        'overeat',
        'person',
        'pregnant',
        'stuffed',
      ],
      '👩‍🍼': [
        'woman_feeding_baby',
        'baby',
        'feed',
        'feeding',
        'mom',
        'mother',
        'nanny',
        'newborn',
        'nursing',
        'woman',
      ],
      '👨‍🍼': [
        'man_feeding_baby',
        'baby',
        'dad',
        'father',
        'feed',
        'feeding',
        'man',
        'nanny',
        'newborn',
        'nursing',
      ],
      '🧑‍🍼': [
        'person_feeding_baby',
        'baby',
        'feed',
        'feeding',
        'nanny',
        'newborn',
        'nursing',
        'parent',
      ],
      '🧌': [
        'troll',
        'fairy',
        'fantasy',
        'monster',
        'tale',
        'troll',
        'trolling',
      ],
      '🫂': [
        'people_hugging',
        'comfort',
        'embrace',
        'farewell',
        'friendship',
        'goodbye',
        'hello',
        'hug',
        'hugging',
        'love',
        'people',
        'thanks',
      ],
      '🚶‍➡️': [
        'person_walking',
        'amble',
        'gait',
        'hike',
        'man',
        'pace',
        'pedestrian',
        'person',
        'stride',
        'stroll',
        'walk',
        'walking',
      ],
      '🚶‍♀️‍➡️': [
        'woman walking',
        'amble',
        'gait',
        'hike',
        'man',
        'pace',
        'pedestrian',
        'stride',
        'stroll',
        'walk',
        'walking',
        'woman',
      ],
      '🚶‍♂️‍➡️': [
        'man_walking',
        'amble',
        'gait',
        'hike',
        'man',
        'pace',
        'pedestrian',
        'stride',
        'stroll',
        'walk',
        'walking',
      ],
      '🧎‍➡️': ['person_kneeling', 'kneel', 'kneeling', 'knees', 'person'],
      '🧎‍♀️‍➡️': ['woman_kneeling', 'kneel', 'kneeling', 'knees', 'woman'],
      '🧎‍♂️‍➡️': ['man_kneeling', 'kneel', 'kneeling', 'knees', 'man'],
      '🧑‍🦯‍➡️': [
        'person_with_white_cane',
        'accessibility',
        'blind',
        'cane',
        'person',
        'probing',
        'white',
      ],
      '👨‍🦯‍➡️': [
        'man_with_white_cane',
        'accessibility',
        'blind',
        'cane',
        'man',
        'probing',
        'white',
      ],
      '👩‍🦯‍➡️': [
        'woman_with_white_cane',
        'accessibility',
        'blind',
        'cane',
        'probing',
        'white',
        'woman',
      ],
      '🧑‍🦼‍➡️': [
        'person_in_motorized_wheelchair',
        'accessibility',
        'motorized',
        'person',
        'wheelchair',
      ],
      '👨‍🦼‍➡️': [
        'man_in_motorized_wheelchair',
        'accessibility',
        'man',
        'motorized',
        'wheelchair',
      ],
      '👩‍🦼‍➡️': [
        'woman_in_motorized_wheelchair',
        'accessibility',
        'motorized',
        'wheelchair',
        'woman',
      ],
      '🧑‍🦽‍➡️': [
        'person_in_manual_wheelchair',
        'accessibility',
        'manual',
        'person',
        'wheelchair',
      ],
      '👨‍🦽‍➡️': [
        'man_in_manual_wheelchair',
        'accessibility',
        'man',
        'manual',
        'wheelchair',
      ],
      '👩‍🦽‍➡️': [
        'woman_in_manual_wheelchair',
        'accessibility',
        'manual',
        'wheelchair',
        'woman',
      ],
      '🏃‍➡️': [
        'person_running',
        'fast',
        'hurry',
        'marathon',
        'move',
        'person',
        'quick',
        'race',
        'racing',
        'run',
        'rush',
        'speed',
      ],
      '🏃‍♀️‍➡️': [
        'woman_running_facing_right',
        'fast',
        'hurry',
        'marathon',
        'move',
        'quick',
        'race',
        'racing',
        'run',
        'rush',
        'speed',
        'woman',
      ],
      '🏃‍♂️‍➡️': [
        'man_running',
        'fast',
        'hurry',
        'man',
        'marathon',
        'move',
        'quick',
        'race',
        'racing',
        'run',
        'rush',
        'speed',
      ],
      '🧑‍🧑‍🧒': ['family_adult_adult_child', 'adult', 'child', 'family'],
      '🧑‍🧑‍🧒‍🧒': [
        'family_adult_adult_child_child',
        'adult',
        'child',
        'family',
      ],
      '🧑‍🧒': ['family_adult_child', 'adult', 'child', 'family'],
      '🧑‍🧒‍🧒': ['family_adult_child_child', 'adult', 'child', 'family'],
      '🐦‍🔥': [
        'phoenix',
        'ascend',
        'ascension',
        'emerge',
        'fantasy',
        'firebird',
        'glory',
        'immortal',
        'phoenix',
        'rebirth',
        'reincarnation',
        'reinvent',
        'renewal',
        'revival',
        'revive',
        'rise',
        'transform',
      ],
      '🪸': ['coral', 'change', 'climate', 'coral', 'ocean', 'reef', 'sea'],
      '🪷': [
        'lotus',
        'beauty',
        'buddhism',
        'calm',
        'flower',
        'hinduism',
        'lotus',
        'peace',
        'purity',
        'serenity',
      ],
      '🪹': ['empty_nest', 'branch', 'empty', 'home', 'nest', 'nesting'],
      '🪺': [
        'nest_with_eggs',
        'bird',
        'branch',
        'egg',
        'eggs',
        'nest',
        'nesting',
      ],
      '🫖': ['teapot', 'brew', 'drink', 'food', 'pot', 'tea', 'teapot'],
      '🫗': [
        'pouring_liquid',
        'accident',
        'drink',
        'empty',
        'glass',
        'liquid',
        'oops',
        'pour',
        'pouring',
        'spill',
        'water',
      ],
      '🩴': [
        'thong sandal',
        'beach',
        'flip',
        'flop',
        'sandal',
        'sandals',
        'shoe',
        'thong',
        'thongs',
        'zōri',
      ],
      '🪖': [
        'military_helmet',
        'army',
        'helmet',
        'military',
        'soldier',
        'war',
        'warrior',
      ],
      '🍋‍🟩': [
        'lime',
        'acidity',
        'citrus',
        'cocktail',
        'fruit',
        'garnish',
        'key',
        'lime',
        'margarita',
        'mojito',
        'refreshing',
        'salsa',
        'sour',
        'tangy',
        'tequila',
        'tropical',
        'zest</annotatio',
      ],
      '🫘': ['beans', 'beans', 'food', 'kidney', 'legume', 'small'],
      '🍄‍🟫': [
        'brown_mushroom',
        'food',
        'fungi',
        'fungus',
        'mushroom',
        'nature',
        'pizza',
        'portobello',
        'shiitake',
        'shroom',
        'spore',
        'sprout',
        'toppings',
        'truffle',
        'vegetable',
        'vegetarian',
        'veggie',
      ],
      '🫙': [
        'jar',
        'condiment',
        'container',
        'empty',
        'jar',
        'nothing',
        'sauce',
        'store',
      ],
      '🪨': ['rock', 'boulder', 'heavy', 'rock', 'solid', 'stone', 'tough'],
      '🪵': ['wood', 'log', 'lumber', 'timber', 'wood'],
      '🛖': ['hut', 'home', 'house', 'hut', 'roundhouse', 'shelter', 'yurt'],
      '🛼': ['roller_skate', 'blades', 'roller', 'skate', 'skates', 'sport'],
      '🛝': [
        'playground slide',
        'amusement',
        'park',
        'play',
        'playground',
        'playing',
        'slide',
        'sliding',
        'theme',
      ],
      '🛞': ['wheel', 'car', 'circle', 'tire', 'turn', 'vehicle', 'wheel'],
      '🛟': [
        'ring_buoy',
        'buoy',
        'float',
        'life',
        'lifesaver',
        'preserver',
        'rescue',
        'ring',
        'safety',
        'save',
        'saver',
        'swim',
      ],
      '🪄': ['magic_wand', 'magic', 'magician', 'wand', 'witch', 'wizard'],
      '🪅': [
        'piñata',
        'candy',
        'celebrate',
        'celebration',
        'cinco',
        'de',
        'festive',
        'mayo',
        'party',
        'pinada',
        'pinata',
        'piñata',
      ],
      '🪩': [
        'mirror_ball',
        'ball',
        'dance',
        'disco',
        'glitter',
        'mirror',
        'party',
      ],
      '🪆': [
        'nesting_dolls',
        'babooshka',
        'baboushka',
        'babushka',
        'doll',
        'dolls',
        'matryoshka',
        'nesting',
        'russia',
      ],
      '🪡': [
        'sewing_needle',
        'embroidery',
        'needle',
        'sew',
        'sewing',
        'stitches',
        'sutures',
        'tailoring',
        'thread',
      ],
      '🪢': [
        'knot',
        'cord',
        'knot',
        'rope',
        'tangled',
        'tie',
        'twine',
        'twist',
      ],
      '⛓️‍💥': [
        'broken_chain',
        'break',
        'breaking',
        'broken',
        'chain',
        'cuffs',
        'freedom',
      ],
      '🩼': [
        'crutch',
        'aid',
        'cane',
        'crutch',
        'disability',
        'help',
        'hurt',
        'injured',
        'mobility',
        'stick',
      ],
      '🩻': [
        'x-ray',
        'bones',
        'doctor',
        'medical',
        'skeleton',
        'skull',
        'x-ray',
        'xray',
      ],
      '🫧': [
        'bubbles',
        'bubble',
        'bubbles',
        'burp',
        'clean',
        'floating',
        'pearl',
        'soap',
        'underwater',
      ],
      '🪦': [
        'headstone',
        'cemetery',
        'dead',
        'grave',
        'graveyard',
        'headstone',
        'memorial',
        'rip',
        'tomb',
        'tombstone',
      ],
      '🪬': [
        'hamsa',
        'amulet',
        'fatima',
        'fortune',
        'guide',
        'hamsa',
        'hand',
        'mary',
        'miriam',
        'palm',
        'protect',
        'protection',
      ],
      '🪧': [
        'placard',
        'card',
        'demonstration',
        'notice',
        'picket',
        'placard',
        'plaque',
        'protest',
        'sign',
      ],
      '🪪': [
        'identification_card',
        'card',
        'credentials',
        'document',
        'ID',
        'identification',
        'license',
        'security',
      ],
      '❤️‍🔥': [
        'heart_on_fire',
        'burn',
        'fire',
        'heart',
        'love',
        'lust',
        'sacred',
      ],
      '❤️‍🩹': [
        'mending_heart',
        'healthier',
        'heart',
        'improving',
        'mending',
        'recovering',
        'recuperating',
        'well',
      ],
      '🟰': [
        'heavy equals sign',
        'answer',
        'equal',
        'equality',
        'equals',
        'heavy',
        'math',
        'sign',
      ],
      '🇦': ['a', 'blue-square', 'alphabet'],
      '🇧': ['b', 'blue-square', 'alphabet'],
      '🇨': ['c', 'blue-square', 'alphabet'],
      '🇩': ['d', 'blue-square', 'alphabet'],
      '🇪': ['e', 'blue-square', 'alphabet'],
      '🇫': ['f', 'blue-square', 'alphabet'],
      '🇬': ['g', 'blue-square', 'alphabet'],
      '🇭': ['h', 'blue-square', 'alphabet'],
      '🇮': ['i', 'blue-square', 'alphabet'],
      '🇯': ['j', 'blue-square', 'alphabet'],
      '🇰': ['k', 'blue-square', 'alphabet'],
      '🇱': ['l', 'blue-square', 'alphabet'],
      '🇲': ['m', 'blue-square', 'alphabet'],
      '🇳': ['n', 'blue-square', 'alphabet'],
      '🇴': ['o', 'blue-square', 'alphabet'],
      '🇵': ['p', 'blue-square', 'alphabet'],
      '🇶': ['q', 'blue-square', 'alphabet'],
      '🇷': ['r', 'blue-square', 'alphabet'],
      '🇸': ['s', 'blue-square', 'alphabet'],
      '🇹': ['t', 'blue-square', 'alphabet'],
      '🇺': ['u', 'blue-square', 'alphabet'],
      '🇻': ['v', 'blue-square', 'alphabet'],
      '🇼': ['w', 'blue-square', 'alphabet'],
      '🇽': ['x', 'blue-square', 'alphabet'],
      '🇾': ['y', 'blue-square', 'alphabet'],
      '🇿': ['z', 'blue-square', 'alphabet'],
    },
    'ja-JP': {
      '🙂‍↔️': ['首を横に振る', 'いいえ', '不賛成', '顔', '首を振る', '首を横に振る'],
      '🙂‍↕️': ['首を縦に振る', 'はい', '頷く', '顔', '首を振る', '首を縦に振る'],
      '🚶‍➡️': [
        '歩く人',
        'ウォーキング',
        'ハイキング',
        'ぶらつく',
        '人',
        '大股',
        '散歩',
        '歩く',
        '歩行',
        '歩行者',
      ],
      '🚶‍♀️‍➡️': [
        '歩く女',
        'ウォーキング',
        'ハイキング',
        '女性',
        '散歩',
        '歩く',
        '歩く女',
        '歩行',
        '歩行者',
      ],
      '🚶‍♂️‍➡️': ['歩く男', 'ウォーキング', '歩く男', '歩行', '歩行者', '男性'],
      '🧎‍➡️': ['正座する人', 'ひざまずく', '人', '座る', '正座する人'],
      '🧎‍♀️‍➡️': ['正座する女性', 'ひざまずく', '女性', '座る', '正座する女性'],
      '🧎‍♂️‍➡️': ['正座する男性', 'ひざまずく', '座る', '正座する男性', '男性'],
      '🧑‍🦯‍➡️': ['杖をついた人', 'アクセシビリティ', '杖をついた人', '目', '視覚', '障がい'],
      '👨‍🦯‍➡️': [
        '杖をついた男性',
        'アクセシビリティ',
        '杖をついた男性',
        '男性',
        '白杖をついた男性',
        '目',
        '視覚',
        '障がい',
      ],
      '👩‍🦯‍➡️': [
        '杖をついた女性',
        'アクセシビリティ',
        '女性',
        '杖をついた女性',
        '白杖をついた女性',
        '目',
        '視覚',
        '障がい',
      ],
      '🧑‍🦼‍➡️': ['電動車椅子の人', 'アクセシビリティ', '車いす', '障がい', '電動車椅子の人'],
      '👨‍🦼‍➡️': ['電動車椅子の男性', 'アクセシビリティ', '男性', '車いす', '障がい', '電動車椅子の男性'],
      '👩‍🦼‍➡️': ['電動車椅子の女性', 'アクセシビリティ', '女性', '車いす', '障がい', '電動車椅子の女性'],
      '🧑‍🦽‍➡️': ['手動式車椅子の人', 'アクセシビリティ', '手動式車椅子の人', '車いす', '障がい'],
      '👨‍🦽‍➡️': ['手動式車椅子の男性', 'アクセシビリティ', '手動式車椅子の男性', '男性', '車いす', '障がい'],
      '👩‍🦽‍➡️': ['手動式車椅子の女性', 'アクセシビリティ', '女性', '手動式車椅子の女性', '車いす', '障がい'],
      '🏃‍➡️': [
        '走る人',
        'ジョギング',
        'マラソン',
        'ランナー',
        'ランニング',
        '急ぐ',
        '走る',
        '走る人',
        '駆け足',
      ],
      '🏃‍♀️‍➡️': [
        '走る女',
        'ジョギング',
        'マラソン',
        'ランナー',
        'ランニング',
        '女性',
        '急ぐ',
        '走る',
        '走る女',
        '駆け足',
      ],
      '🏃‍♂️‍➡️': ['走る男', 'ジョギング', 'マラソン', 'ランナー', 'ランニング', '男性', '走る男'],
      '🧑‍🧑‍🧒': [
        '家族（大人二人と子供一人）',
        '大人二人',
        '子供一人',
        '家族',
        '家族（大人二人と子供一人）',
        '親子',
      ],
      '🧑‍🧑‍🧒‍🧒': [
        '家族（大人二人と子供二人）',
        '大人二人',
        '子供二人',
        '家族',
        '家族（大人二人と子供二人）',
        '親子',
      ],
      '🧑‍🧒': ['家族（大人一人と子供一人）', '大人一人', '子供一人', '家族', '家族（大人一人と子供一人）', '親子'],
      '🧑‍🧒‍🧒': [
        '家族（大人一人と子供二人）',
        '大人一人',
        '子供二人',
        '家族',
        '家族（大人一人と子供二人）',
        '親子',
      ],
      '🐦‍🔥': [
        'フェニックス',
        'ファンタジー',
        'フェニックス',
        '不死鳥',
        '再生',
        '復活',
        '火の鳥',
        '生まれ変わり',
        '神話',
        '転生',
        '輪廻',
      ],
      '🍋‍🟩': [
        'ライム',
        'さわやか',
        'トロピカル',
        'フルーツ',
        'マルガリータ',
        'モヒート',
        'ライム',
        '果物',
        '柑橘類',
        '緑',
        '酸っぱい',
      ],
      '🍄‍🟫': [
        'きのこ',
        'きのこ',
        'キノコ',
        'しいたけ',
        'トリュフ',
        'ブラウンマッシュルーム',
        'ポートベロー',
        'マッシュルーム',
        '椎茸',
        '茸',
        '菌類',
      ],
      '⛓️‍💥': ['壊れた鎖', 'くさり', 'チェーン', '壊れた', '壊れた鎖'],
      '🇦': ['a', 'アルファベット'],
      '🇧': ['b', 'アルファベット'],
      '🇨': ['c', 'アルファベット'],
      '🇩': ['d', 'アルファベット'],
      '🇪': ['e', 'アルファベット'],
      '🇫': ['f', 'アルファベット'],
      '🇬': ['g', 'アルファベット'],
      '🇭': ['h', 'アルファベット'],
      '🇮': ['i', 'アルファベット'],
      '🇯': ['j', 'アルファベット'],
      '🇰': ['k', 'アルファベット'],
      '🇱': ['l', 'アルファベット'],
      '🇲': ['m', 'アルファベット'],
      '🇳': ['n', 'アルファベット'],
      '🇴': ['o', 'アルファベット'],
      '🇵': ['p', 'アルファベット'],
      '🇶': ['q', 'アルファベット'],
      '🇷': ['r', 'アルファベット'],
      '🇸': ['s', 'アルファベット'],
      '🇹': ['t', 'アルファベット'],
      '🇺': ['u', 'アルファベット'],
      '🇻': ['v', 'アルファベット'],
      '🇼': ['w', 'アルファベット'],
      '🇽': ['x', 'アルファベット'],
      '🇾': ['y', 'アルファベット'],
      '🇿': ['z', 'アルファベット'],
    },
    'ja-JP_hira': {
      '🙂‍↔️': ['くびをよこにふる', 'いいえ', 'ふさんせい', 'かお', 'くびをふる', 'くびをよこにふる'],
      '🙂‍↕️': ['くびをたてにふる', 'はい', 'うなずく', 'かお', 'くびをふる', 'くびをたてにふる'],
      '🚶‍➡️': [
        'あるくひと',
        'うぉーきんぐ',
        'はいきんぐ',
        'ぶらつく',
        'ひと',
        'おおまた',
        'さんぽ',
        'あるく',
        'ほこう',
        'ほこうしゃ',
      ],
      '🚶‍♀️‍➡️': [
        'あるくおんな',
        'うぉーきんぐ',
        'はいきんぐ',
        'じょせい',
        'さんぽ',
        'あるく',
        'あるくおんな',
        'ほこう',
        'ほこうしゃ',
      ],
      '🚶‍♂️‍➡️': ['あるくおとこ', 'うぉーきんぐ', 'あるくおとこ', 'ほこう', 'ほこうしゃ', 'だんせい'],
      '🧎‍➡️': ['せいざするひと', 'ひざまずく', 'ひと', 'すわる', 'せいざするひと'],
      '🧎‍♀️‍➡️': ['せいざするじょせい', 'ひざまずく', 'じょせい', 'すわる', 'せいざするじょせい'],
      '🧎‍♂️‍➡️': ['せいざするだんせい', 'ひざまずく', 'すわる', 'せいざするだんせい', 'だんせい'],
      '🧑‍🦯‍➡️': ['つえをついたひと', 'あくせしびりてぃ', 'つえをついたひと', 'め', 'しかく', 'しょうがい'],
      '👨‍🦯‍➡️': [
        'つえをついただんせい',
        'あくせしびりてぃ',
        'つえをついただんせい',
        'だんせい',
        'はくじょうをついただんせい',
        'め',
        'しかく',
        'しょうがい',
      ],
      '👩‍🦯‍➡️': [
        'つえをついたじょせい',
        'あくせしびりてぃ',
        'じょせい',
        'つえをついたじょせい',
        'はくじょうをついたじょせい',
        'め',
        'しかく',
        'しょうがい',
      ],
      '🧑‍🦼‍➡️': [
        'でんどうくるまいすのひと',
        'あくせしびりてぃ',
        'くるまいす',
        'しょうがい',
        'でんどうくるまいすのひと',
      ],
      '👨‍🦼‍➡️': [
        'でんどうくるまいすのだんせい',
        'あくせしびりてぃ',
        'だんせい',
        'くるまいす',
        'しょうがい',
        'でんどうくるまいすのだんせい',
      ],
      '👩‍🦼‍➡️': [
        'でんどうくるまいすのじょせい',
        'あくせしびりてぃ',
        'じょせい',
        'くるまいす',
        'しょうがい',
        'でんどうくるまいすのじょせい',
      ],
      '🧑‍🦽‍➡️': [
        'しゅどうしきくるまいすのひと',
        'あくせしびりてぃ',
        'しゅどうしきくるまいすのひと',
        'くるまいす',
        'しょうがい',
      ],
      '👨‍🦽‍➡️': [
        'しゅどうしきくるまいすのだんせい',
        'あくせしびりてぃ',
        'しゅどうしきくるまいすのだんせい',
        'だんせい',
        'くるまいす',
        'しょうがい',
      ],
      '👩‍🦽‍➡️': [
        'しゅどうしきくるまいすのじょせい',
        'あくせしびりてぃ',
        'じょせい',
        'しゅどうしきくるまいすのじょせい',
        'くるまいす',
        'しょうがい',
      ],
      '🏃‍➡️': [
        'はしるひと',
        'じょぎんぐ',
        'まらそん',
        'らんなー',
        'らんにんぐ',
        'いそぐ',
        'はしる',
        'はしるひと',
        'かけあし',
      ],
      '🏃‍♀️‍➡️': [
        'はしるおんな',
        'じょぎんぐ',
        'まらそん',
        'らんなー',
        'らんにんぐ',
        'じょせい',
        'いそぐ',
        'はしる',
        'はしるおんな',
        'かけあし',
      ],
      '🏃‍♂️‍➡️': [
        'はしるおとこ',
        'じょぎんぐ',
        'まらそん',
        'らんなー',
        'らんにんぐ',
        'だんせい',
        'はしるおとこ',
      ],
      '🧑‍🧑‍🧒': [
        'かぞく（おとなふたりとこどもひとり）',
        'おとなふたり',
        'こどもひとり',
        'かぞく',
        'かぞく（おとなふたりとこどもひとり）',
        'おやこ',
      ],
      '🧑‍🧑‍🧒‍🧒': [
        'かぞく（おとなふたりとこどもふたり）',
        'おとなふたり',
        'こどもふたり',
        'かぞく',
        'かぞく（おとなふたりとこどもふたり）',
        'おやこ',
      ],
      '🧑‍🧒': [
        'かぞく（おとなひとりとこどもひとり）',
        'おとなひとり',
        'こどもひとり',
        'かぞく',
        'かぞく（おとなひとりとこどもひとり）',
        'おやこ',
      ],
      '🧑‍🧒‍🧒': [
        'かぞく（おとなひとりとこどもふたり）',
        'おとなひとり',
        'こどもふたり',
        'かぞく',
        'かぞく（おとなひとりとこどもふたり）',
        'おやこ',
      ],
      '🐦‍🔥': [
        'ふぇにっくす',
        'ふぁんたじー',
        'ふぇにっくす',
        'ふしちょう',
        'さいせい',
        'ふっかつ',
        'ひのとり',
        'うまれかわり',
        'しんわ',
        'てんせい',
        'りんね',
      ],
      '🍋‍🟩': [
        'らいむ',
        'さわやか',
        'とろぴかる',
        'ふるーつ',
        'まるがりーた',
        'もひーと',
        'らいむ',
        'くだもの',
        'かんきつるい',
        'みどり',
        'すっぱい',
      ],
      '🍄‍🟫': [
        'きのこ',
        'きのこ',
        'きのこ',
        'しいたけ',
        'とりゅふ',
        'ぶらうんまっしゅるーむ',
        'ぽーとべろー',
        'まっしゅるーむ',
        'しいたけ',
        'きのこ',
        'きんるい',
      ],
      '⛓️‍💥': ['こわれたくさり', 'くさり', 'ちぇーん', 'こわれた', 'こわれたくさり'],
      '🇦': ['a', 'あるふぁべっと'],
      '🇧': ['b', 'あるふぁべっと'],
      '🇨': ['c', 'あるふぁべっと'],
      '🇩': ['d', 'あるふぁべっと'],
      '🇪': ['e', 'あるふぁべっと'],
      '🇫': ['f', 'あるふぁべっと'],
      '🇬': ['g', 'あるふぁべっと'],
      '🇭': ['h', 'あるふぁべっと'],
      '🇮': ['i', 'あるふぁべっと'],
      '🇯': ['j', 'あるふぁべっと'],
      '🇰': ['k', 'あるふぁべっと'],
      '🇱': ['l', 'あるふぁべっと'],
      '🇲': ['m', 'あるふぁべっと'],
      '🇳': ['n', 'あるふぁべっと'],
      '🇴': ['o', 'あるふぁべっと'],
      '🇵': ['p', 'あるふぁべっと'],
      '🇶': ['q', 'あるふぁべっと'],
      '🇷': ['r', 'あるふぁべっと'],
      '🇸': ['s', 'あるふぁべっと'],
      '🇹': ['t', 'あるふぁべっと'],
      '🇺': ['u', 'あるふぁべっと'],
      '🇻': ['v', 'あるふぁべっと'],
      '🇼': ['w', 'あるふぁべっと'],
      '🇽': ['x', 'あるふぁべっと'],
      '🇾': ['y', 'あるふぁべっと'],
      '🇿': ['z', 'あるふぁべっと'],
    },
  };
  final categorized = <String, List<String>>{};
  final textToEmoji = SplayTreeMap<String, Set<String>>();
  final emojis = [
    ...jsonDecode(
          File(
            'misskey/packages/frontend-shared/js/emojilist.json',
          ).readAsStringSync(),
        )
        as List,
    ...emojilist,
  ];
  for (final emoji in emojis) {
    final char = (emoji as List)[0] as String;
    final name = emoji[1] as String;
    final category = categories[emoji[2] as int];
    categorized.putIfAbsent(category, () => []).add(char);
    textToEmoji.putIfAbsent(name, () => {}).add(char);
  }
  final categorizedEmojisFile = File(
    'lib/constant/categorized_unicode_emojis.g.dart',
  );
  categorizedEmojisFile.writeAsStringSync("""
/// Generated file. Do not edit.
///
/// Source: misskey/packages/frontend-shared/js/emojilist.json
/// To regenerate, run: `flutter run script/gen_unicode_emoji_index.dart`

const categorizedUnicodeEmojis = ${const JsonEncoder.withIndent('  ').convert(categorized)};
""");
  // ignore: avoid_print
  print('Successfully generated ${categorizedEmojisFile.path}');

  const languages = ['en-US', 'ja-JP', 'ja-JP_hira'];
  for (final language in languages) {
    final emojiToText = {
      ...jsonDecode(
            File(
              'misskey/packages/frontend/src/unicode-emoji-indexes/$language.json',
            ).readAsStringSync(),
          )
          as Map<String, dynamic>,
      ...?unicodeEmojiIndexes[language],
    };
    for (final entry in emojiToText.entries) {
      for (final text in entry.value as List) {
        textToEmoji.putIfAbsent(text as String, () => {}).add(entry.key);
      }
    }
  }
  final emojiIndexFile = File('lib/constant/unicode_emoji_index.g.dart');
  emojiIndexFile.writeAsStringSync("""
/// Generated file. Do not edit.
///
/// Source: misskey/packages/frontend-shared/js/emojilist.json
/// Source: misskey/packages/frontend/src/unicode-emoji-indexes
/// To regenerate, run: `flutter run script/gen_unicode_emoji_index.dart`

const unicodeEmojiIndex = {
${textToEmoji.entries.map((e) => "  '${e.key.replaceAll("'", r"\'")}': ${jsonEncode(e.value.toList())}").join(',\n')}
};
""");
  // ignore: avoid_print
  print('Successfully generated ${emojiIndexFile.path}');
}
