import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

extension SearchInputDecorationExtension on SearchInputDecoration {
  SearchInputDecoration applyInputDecoration(InputDecoration inputDecoration) {
    return copyWith(
      prefixIconConstraints: inputDecoration.prefixIconConstraints,
      suffixIconConstraints: inputDecoration.suffixIconConstraints,
      hintMaxLines: inputDecoration.hintMaxLines,
      floatingLabelStyle: inputDecoration.floatingLabelStyle,
      errorText: inputDecoration.errorText,
      error: inputDecoration.error,
      hintTextDirection: inputDecoration.hintTextDirection,
      hintFadeDuration: inputDecoration.hintFadeDuration,
      helper: inputDecoration.helper,
      alignLabelWithHint: inputDecoration.alignLabelWithHint,
      border: inputDecoration.border,
      constraints: inputDecoration.constraints,
      contentPadding: inputDecoration.contentPadding,
      counter: inputDecoration.counter,
      counterStyle: inputDecoration.counterStyle,
      counterText: inputDecoration.counterText,
      disabledBorder: inputDecoration.disabledBorder,
      enabledBorder: inputDecoration.enabledBorder,
      errorBorder: inputDecoration.errorBorder,
      errorMaxLines: inputDecoration.errorMaxLines,
      errorStyle: inputDecoration.errorStyle,
      fillColor: inputDecoration.fillColor,
      filled: inputDecoration.filled,
      floatingLabelAlignment: inputDecoration.floatingLabelAlignment,
      floatingLabelBehavior: inputDecoration.floatingLabelBehavior,
      focusColor: inputDecoration.focusColor,
      focusedBorder: inputDecoration.focusedBorder,
      focusedErrorBorder: inputDecoration.focusedErrorBorder,
      helperMaxLines: inputDecoration.helperMaxLines,
      helperStyle: inputDecoration.helperStyle,
      helperText: inputDecoration.helperText,
      hintStyle: inputDecoration.hintStyle,
      hintText: inputDecoration.hintText,
      hoverColor: inputDecoration.hoverColor,
      icon: inputDecoration.icon,
      iconColor: inputDecoration.iconColor,
      isCollapsed: inputDecoration.isCollapsed,
      isDense: inputDecoration.isDense,
      label: inputDecoration.label,
      labelStyle: inputDecoration.labelStyle,
      labelText: inputDecoration.labelText,
      prefix: inputDecoration.prefix,
      prefixIcon: inputDecoration.prefixIcon,
      prefixIconColor: inputDecoration.prefixIconColor,
      prefixStyle: inputDecoration.prefixStyle,
      prefixText: inputDecoration.prefixText,
      semanticCounterText: inputDecoration.semanticCounterText,
      suffix: inputDecoration.suffix,
      suffixIcon: inputDecoration.suffixIcon,
      suffixIconColor: inputDecoration.suffixIconColor,
      suffixStyle: inputDecoration.suffixStyle,
      suffixText: inputDecoration.suffixText,
    );
  }
}
