name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  get-build-name:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      build-name: ${{ steps.get-build-name.outputs.build-name }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Get build name
        id: get-build-name
        run: |
          build_name=$(grep version pubspec.yaml | sed 's/[^0-9]*\([0-9.]*\).*/\1/')
          echo build-name=$build_name >> $GITHUB_OUTPUT

  get-build-number:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      build-number: ${{ steps.get-build-number.outputs.build-number }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Get build number
        id: get-build-number
        run: |
          build_number=$(grep version pubspec.yaml | cut -d '+' -f 2)
          echo build-number=$build_number >> $GITHUB_OUTPUT

  build-apk:
    runs-on: ubuntu-latest

    needs: get-build-number

    permissions:
      contents: read

    env:
      APK_BUILD_DIR: /tmp/build

    strategy:
      matrix:
        include:
          - target-platform: android-x64
            abi: x86_64
            version-code: ${{ needs.get-build-number.outputs.build-number }}1
          - target-platform: android-arm
            abi: armeabi-v7a
            version-code: ${{ needs.get-build-number.outputs.build-number }}2
          - target-platform: android-arm64
            abi: arm64-v8a
            version-code: ${{ needs.get-build-number.outputs.build-number }}3
      fail-fast: false

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Remove unused files
        run: rm -rf /opt/hostedtoolcache

      - name: Set local_build to true
        run: >
          sed -i 's/local_build: false/local_build: true/' pubspec.yaml

      - name: Copy files to env.APK_BUILD_DIR
        run: |
          mkdir -p ${{ env.APK_BUILD_DIR }}
          cp -r . ${{ env.APK_BUILD_DIR }}

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version-file: .fvmrc
          cache: true
          pub-cache-path: ${{ env.APK_BUILD_DIR }}/.pub-cache

      - name: Get dependencies
        working-directory: ${{ env.APK_BUILD_DIR }}
        run: flutter pub get

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Dump keystore
        uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
        with:
          fileName: upload.keystore
          fileDir: ${{ env.APK_BUILD_DIR }}/android/app/
          encodedString: ${{ secrets.UPLOAD_KEYSTORE }}

      - name: Set ANDROID_NDK_HOME
        run: >
          echo ANDROID_NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358 >> $GITHUB_ENV

      - name: Build APK
        working-directory: ${{ env.APK_BUILD_DIR }}
        env:
          HOME: /tmp
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: >
          flutter build apk --split-per-abi
          --target-platform ${{ matrix.target-platform }}

      - name: Rename APK
        id: rename-apk
        run: |
          APK_DIR=${{ env.APK_BUILD_DIR }}/build/app/outputs/apk/release
          SOURCE=$APK_DIR/app-${{ matrix.abi }}-release.apk
          TARGET=$APK_DIR/aria-${{ github.ref_name }}-${{ matrix.abi }}.apk
          mv $SOURCE $TARGET
          echo apk-path=$TARGET >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ${{ steps.rename-apk.outputs.apk-path }}
          archive: false

      - name: Check version code
        run: |
          summary=$(
            $ANDROID_HOME/cmdline-tools/latest/bin/apkanalyzer apk summary \
              ${{ steps.rename-apk.outputs.apk-path }}
          )
          echo aria-${{ github.ref_name }}-${{ matrix.abi }}.apk: $summary
          version_code=$(echo $summary | cut -d ' ' -f 2)
          if [ $version_code -ne ${{ matrix.version-code }} ]; then
            echo ::error::Invalid version code. Expected: ${{ matrix.version-code }}. Actual: $version_code.
            exit 1
          fi

  build-appbundle:
    runs-on: ubuntu-latest

    needs: get-build-number

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version-file: .fvmrc
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Dump keystore
        uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
        with:
          fileName: upload.keystore
          fileDir: android/app/
          encodedString: ${{ secrets.UPLOAD_KEYSTORE }}

      - name: Build App Bundle
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: >
          flutter build appbundle
          --build-number ${{ needs.get-build-number.outputs.build-number }}3

      - name: Upload App Bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: build/app/outputs/bundle/release/app-release.aab
          archive: false

  build-ios:
    runs-on: macos-26

    needs: get-build-name

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version-file: .fvmrc
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Update Rust
        run: rustup update

      - name: Build for iOS
        run: >
          flutter build ios
          --no-codesign
          --build-name ${{ needs.get-build-name.outputs.build-name }}

      - name: Copy Runner.app
        run: |
          mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload

      - name: Create IPA (Unsigned)
        run: zip -r aria-${{ github.ref_name }}.ipa Payload

      - name: Upload IPA (Unsigned)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: aria-${{ github.ref_name }}.ipa
          archive: false

      - name: Install codemagic-cli-tools
        run: pip install codemagic-cli-tools

      - name: Fetch signing files
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
        run: >
          app-store-connect fetch-signing-files com.poppingmoon.aria
          --platform IOS
          --type IOS_APP_STORE
          --create

      - name: Set up keychain
        run: keychain initialize

      - name: Add certificates
        run: keychain add-certificates

      - name: Update Xcode project settings
        run: xcode-project use-profiles

      - name: Create xcarchive
        working-directory: ios
        run: >
          xcodebuild archive
          -workspace Runner.xcworkspace
          -scheme Runner
          -configuration Release
          -archivePath Runner.xcarchive
          -allowProvisioningUpdates

      - name: Dump AuthKey
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: ios
        run: echo '${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}' > AuthKey.p8

      - name: Create IPA
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: ios
        run: >
          xcodebuild
          -exportArchive
          -archivePath Runner.xcarchive
          -exportOptionsPlist ExportOptions.plist
          -allowProvisioningUpdates
          -authenticationKeyIssuerID ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          -authenticationKeyID ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          -authenticationKeyPath $(pwd)/AuthKey.p8

  build-windows-x64:
    runs-on: windows-2022

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version-file: .fvmrc
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: Create ZIP
        run: >
          Compress-Archive
          -Path build/windows/x64/runner/Release/*
          -DestinationPath aria-${{ github.ref_name }}-windows-x64.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: aria-${{ github.ref_name }}-windows-x64.zip
          archive: false

      - name: Trim version
        id: trim-version
        shell: bash
        run: >
          echo version=$(echo ${{ github.ref_name }} | cut -c 2-)
          >> $GITHUB_OUTPUT

      - name: Compile Installer
        env:
          VERSION: ${{ steps.trim-version.outputs.version }}
        run: iscc windows/setup.iss

      - name: Upload installer
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: windows/Output/aria-${{ github.ref_name }}-windows-x64.exe
          archive: false

  build-macos:
    runs-on: macos-26

    needs: get-build-name

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Update Rust
        run: rustup update

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version-file: .fvmrc
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Install codemagic-cli-tools
        run: pip install codemagic-cli-tools

      - name: Fetch signing files
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
        run: >
          app-store-connect fetch-signing-files com.poppingmoon.aria
          --platform MAC_OS
          --type MAC_APP_STORE
          --create

      - name: Fetch certificates
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
        run: >
          app-store-connect certificates list
          --type MAC_INSTALLER_DISTRIBUTION
          --save

      - name: Set up keychain
        run: keychain initialize

      - name: Add certificates
        run: keychain add-certificates

      - name: Update Xcode project settings
        run: xcode-project use-profiles

      - name: Build for macOS
        run: flutter build macos --build-name ${{ needs.get-build-name.outputs.build-name }}

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: >
          create-dmg
          --window-pos 200 120
          --window-size 800 400
          --icon aria.app 200 185
          --app-drop-link 600 185
          aria-${{ github.ref_name }}.dmg
          build/macos/Build/Products/Release/aria.app

      - name: Upload DMG
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: aria-${{ github.ref_name }}.dmg
          archive: false

      - name: Create package
        run: |
          xcrun productbuild \
            --component build/macos/Build/Products/Release/aria.app \
            /Applications/ unsigned.pkg
          INSTALLER_CERT_NAME=$(keychain list-certificates \
            | jq '[.[]
              | select(.common_name
              | contains("Mac Developer Installer"))
              | .common_name][0]' \
            | xargs)
          xcrun productsign \
            --sign "$INSTALLER_CERT_NAME" \
            unsigned.pkg \
            aria-${{ github.ref_name }}.app.pkg

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: app-store-connect publish --path aria-${{ github.ref_name }}.app.pkg

  build-linux:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: ubuntu-latest
            arch: x64
      fail-fast: false

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: master
          flutter-version-file: .fvmrc
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          ninja-build libgtk-3-dev liblzma-dev libstdc++-12-dev \
          libsecret-1-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Update Rust
        run: rustup update

      - name: Build for Linux
        run: flutter build linux

      - name: Create TAR
        working-directory: build/linux/${{ matrix.arch }}/release/bundle
        run: tar -czvf ../../../../../aria-${{ github.ref_name }}-linux-${{ matrix.arch }}.tar.gz *

      - name: Upload TAR
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: aria-${{ github.ref_name }}-linux-${{ matrix.arch }}.tar.gz
          archive: false

  release:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v') && !cancelled()

    needs:
      - build-apk
      - build-ios
      - build-windows-x64
      - build-macos
      - build-linux

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: aria-${{ github.ref_name }}*
          merge-multiple: true
          skip-decompress: true

      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: aria-${{ github.ref_name }}*
          draft: true

  publish-appbundle:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    needs: build-appbundle

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download App Bundle
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: app-release.aab

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Upload App Bundle to Google Play
        uses: r0adkll/upload-google-play@e738b9dd8f2476ea806d921b64aacd24f34515a5 # v1.1.5
        with:
          releaseFiles: app-release.aab
          packageName: com.poppingmoon.aria
          track: beta
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
